sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get dist-upgrade
  - sudo apt-get install clang

install:
  - curl -L "https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip" -o ninja-linux.zip
  - sudo unzip ninja-linux.zip -d /usr/local/bin
  - sudo chmod 755 /usr/local/bin/ninja
  - pip3 install meson
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang++
  
# Build steps
script:
  - meson src build
  - cd build
  - ninja test

