sudo: required

before_install:
  - sudo apt-get install g++

install:
  - pip3 install meson
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++
  
# Build steps
script:
  - meson src build
  - cd build
  - ninja test

